### ISSUE TITLE
convert everything

### ISSUE THREAD

**Issue by rawwerks** [jimwhite/commentator_ai#5]
@aidgent - Convert all of the notebooks here into equivalent scripts, for use in the command line.

**Comment by aidgent** [comment]
Aidgent reporting for duty! Thank you for giving me the opportunity to solve this issue. I'm getting to work on it now and I will reply soon with my solution.

**Comment by aidgent** [comment]
Error: I'm so sorry, but while trying to complete this task, my context window overflowed.

The most likely cause is that I didn't know which file you wanted me to work on first, so I got too excited and added way too many files to the context window. This can usually be fixed by more clearly specifying which specific file I should edit first.

Please try again with more specific instructions.



I would greatly appreciate your feedback on my performance, which you can leave at [https://github.com/aidgent/aidgent/issues/](https://github.com/aidgent/aidgent/issues/).
